$ErrorActionPreference = 'Stop'
$outPath = Join-Path $PSScriptRoot 'SE3090_LifeLink_Student2_Individual_Report_EDITABLE.docx'
$htmlPath = Join-Path $env:TEMP ('lifelink-student2-report-' + [guid]::NewGuid().ToString('N') + '.html')
$html = @'
<!DOCTYPE html><html><head><meta charset="utf-8"><style>
@page { size:A4; margin:1.8cm 2cm; }
body { font-family:'Times New Roman',serif; color:#000; font-size:12pt; line-height:1.18; }
h1 { font-family:'Times New Roman',serif; font-size:16pt; color:#000; margin:15pt 0 6pt; page-break-after:avoid; }
h2 { font-family:'Times New Roman',serif; font-size:14pt; color:#000; margin:11pt 0 4pt; page-break-after:avoid; }
h3 { font-family:'Times New Roman',serif; font-size:12pt; color:#000; margin:8pt 0 3pt; }
p,li,td,th { font-size:12pt; color:#000; }
p { margin:4pt 0 7pt; } li { margin:2pt 0; }
table { border-collapse:collapse; width:100%; margin:7pt 0 10pt; }
td,th { border:1px solid #000; padding:4pt; vertical-align:top; }
th { font-weight:bold; text-align:left; }
a { color:#000; text-decoration:underline; }
.cover { text-align:center; padding-top:75pt; page-break-after:always; }
.cover h1 { font-size:24pt; }
.evidence { border:1px dashed #000; padding:7pt; margin:7pt 0; }
.note { border:1px solid #000; padding:7pt; margin:7pt 0; }
code { font-family:Consolas,monospace; font-size:10pt; }
</style></head><body>
<div class="cover"><p><b>SE3090 · ASSIGNMENT 1</b></p><h1>LifeLink Individual Contribution Report</h1><p><b>Hospital Requests and Triage · Coordinator Agent</b></p><p>Editable individual report</p><p style="margin-top:55pt">Student name: [ENTER YOUR FULL NAME]<br/>Student ID: [ENTER ID]<br/>Group: [ENTER GROUP]<br/>Module / tutor: [ENTER DETAILS]<br/>Submission date: [ENTER DATE]</p><p style="margin-top:40pt">Prepared from the assignment guidance and LifeLink project repository. Complete bracketed fields, attach authentic evidence, and confirm each personal contribution before submission.</p></div>
<h1 id="contents">Contents</h1><ol>
<li><a href="#s1">Contribution Statement</a></li><li><a href="#s2">Owned Component</a></li><li><a href="#s3">Technical Implementation</a></li><li><a href="#s4">Backend/API Evidence</a></li><li><a href="#s5">Database Evidence</a></li><li><a href="#s6">React Evidence</a></li><li><a href="#s7">Flutter Evidence</a></li><li><a href="#s8">Agentic AI Contribution</a></li><li><a href="#s9">Testing Evidence</a></li><li><a href="#s10">Git/PR Evidence</a></li><li><a href="#s11">Challenges &amp; Learning</a></li><li><a href="#s12">Individual AI Usage Log</a></li><li><a href="#s13">AI Reflection</a></li><li><a href="#s14">Signed Declaration</a></li></ol>
<p><b>Evidence note:</b> this report records what can be checked in the repository and leaves personal authorship, test-run results and PR history for you to verify. Do not present team work as your individual work without evidence.</p>

<h1 id="s1">1. Contribution Statement</h1>
<p>The project ownership record assigns Student 2 to <b>Hospital Requests and Triage</b> and the <b>Coordinator Agent</b> [1]. My personal work in this assigned area was: [describe the implementation, design, testing, review and integration work you actually completed]. The system feature provides a traceable path for a hospital to submit a blood request and for authorized staff to review its urgency and status. The Coordinator Agent prepares a bounded plan that the other workflow stages can carry out as proposals. Human administrators remain responsible for approval and dispatch decisions.</p>
<div class="evidence"><b>Insert Evidence 1 — Ownership:</b> attach the project board, group allocation or contribution record that connects your own name/ID to this component and agent. Add the source and date.</div>

<h1 id="s2">2. Owned Component</h1>
<h2>2.1 Hospital requests</h2><p>A hospital requester must be linked to a hospital profile. The hospital registration record includes an official registration number, address, optional coordinates and verification status. Only a verified hospital can submit or update requests. A request records blood type, quantity, urgency, notes, a required-by time, current status, requester and hospital.</p>
<h2>2.2 Triage and lifecycle</h2><p>The request moves through states such as Submitted, UnderReview, PendingApproval, Approved, Dispatched, Fulfilled, Escalated and ClosedUnfulfilled. Only defined transitions are accepted. Before approval, a hospital may correct, escalate or withdraw its request. After approval, the API protects committed operations; dispatch also removes units from inventory in the same relational transaction. The request history records the old and new state, actor, reason and time.</p>
<h2>2.3 Why the feature matters</h2><p>Blood requests are time-sensitive and need enough structure for a blood bank to assess what is required, when it is needed and how the request is progressing. A shared status trail can reduce uncertainty between the requesting hospital and the blood bank. Verification, bounded inputs and explicit human approval are important because an incorrect request or unauthorized action could lead to unsafe resource handling. LifeLink is a coordination prototype, not a clinical triage authority or a replacement for established transfusion services.</p>
<p>ADR-01 assigns this domain and agent pairing to Student 2. It also says cross-cutting work must identify its implementer and reviewer and that student numbers need to be mapped to actual identities by the group [1].</p>

<h1 id="s3">3. Technical Implementation</h1>
<h2>3.1 Request intake and urgency</h2><p>The API validates blood type, urgency, quantity, notes and required-by time. The service converts the requested time to UTC and trims or clears blank notes. The required time must be in the future and within 30 days; quantity must be 1–100. Urgency is calculated from time remaining and requested quantity, then the higher of the user-provided and calculated levels is retained. In the implementation, a request due within two hours or for at least six units is Critical; one due within twelve hours or for at least three units is Urgent; otherwise it is Routine. This is an operational rule in the project, not a clinical standard.</p>
<h2>3.2 Workflow hand-off</h2><p>After a valid request is stored, the request service invokes an <code>IRequestWorkflowTrigger</code> with a reason such as request-created, request-updated or request-escalated. The workflow service creates a numbered execution, sends a structured request to the agent service, and persists plan, steps, outcome and approvals. Edits made before approval supersede an earlier proposal and request a new analysis. Withdrawing a request retires a pending proposal and releases any held reservation in the covered lifecycle paths.</p>
<h2>3.3 Failure and action controls</h2><p>The agent proposes a plan but cannot itself approve or dispatch. The workflow service validates agent output again, checks reservation quantity against remaining demand, checks recipients against active eligible donors of the requested type, and records an approval decision. The request API applies allowed-transition rules. Dispatch is protected by a database transaction and request-row lock in relational operation so stock removal and status change commit together. A failed action is surfaced as an error or escalation rather than being reported as completed.</p>

<h1 id="s4">4. Backend/API Evidence</h1><p>Primary source files are <code>backend/LifeLink.Api/Controllers/RequestsController.cs</code>, <code>backend/LifeLink.Application/Requests/RequestContracts.cs</code>, <code>backend/LifeLink.Infrastructure/Requests/RequestService.cs</code>, <code>backend/LifeLink.Infrastructure/Workflows/WorkflowService.cs</code> and <code>backend/LifeLink.Api/Controllers/AgentWorkflowsController.cs</code>.</p>
<table><tr><th>Route / behavior</th><th>Evidence and authorization</th></tr><tr><td><code>POST /api/requests</code></td><td>HospitalRequester-only. Creates a request for the signed-in user’s linked, verified hospital.</td></tr><tr><td><code>GET /api/requests</code> and <code>GET /{id}</code></td><td>Admins can filter across hospitals; hospital staff are limited to their own hospital. Request-level access is checked before returning details/history.</td></tr><tr><td><code>PUT /{id}</code>, <code>DELETE /{id}</code>, <code>POST /{id}/escalate</code></td><td>Hospital requester actions are limited to its own request and pre-approval states; escalation reason is bounded.</td></tr><tr><td><code>PUT /{id}/status</code></td><td>Admin-only. Status transitions are checked; dispatch couples inventory change and request transition.</td></tr><tr><td><code>GET /{id}/history</code>, <code>GET /reports/summary</code></td><td>History is access-checked. Summary is scoped to the signed-in hospital for non-admin users.</td></tr></table>
<p>The API returns conflict responses for invalid transitions, closed requests, pending workflows and similar state conflicts. Input data annotations complement the deeper service rules. Pagination is clamped to a maximum page size of 100.</p>
<div class="evidence"><b>Insert Evidence 2 — Backend/API:</b> capture the request controller or service validation, plus a redacted request/response from Swagger or an API client. Show route and role context, not access tokens or personal data.</div>

<h1 id="s5">5. Database Evidence</h1><p>Core entities are in <code>backend/LifeLink.Domain/Entities/DonorHospitalEntities.cs</code> and <code>backend/LifeLink.Domain/Entities/WorkflowEntities.cs</code>. Relevant PostgreSQL tables configured in <code>LifeLinkDbContext.cs</code> include <code>hospitals</code>, <code>hospital_staff</code>, <code>blood_requests</code>, <code>request_status_history</code>, <code>agent_workflow_executions</code>, <code>agent_steps</code> and <code>agent_approvals</code>.</p>
<p>A hospital may have multiple staff links; each staff user is uniquely linked to one hospital profile in the current mapping. A blood request references its hospital and requesting user. Request history references the request and the user who made the change. Workflow executions reference a request and have a unique attempt number per request; their correlation ID is unique. Agent steps use unique workflow-and-sequence pairs, while approval records use unique workflow-and-version pairs. Foreign keys use restrictive delete behavior to preserve referenced operational records. Request quantity has a positive-value check constraint, and the status/urgency pair and hospital/creation-time are indexed for common triage queries.</p>
<p>These are schema facts from EF Core configuration. A production database still needs migration and constraint verification, backup/retention design and operational monitoring. Avoid placing unnecessary personal or clinical details in free-text notes.</p>
<div class="evidence"><b>Insert Evidence 3 — Database/EER:</b> add the relevant EER subset showing Hospital, HospitalStaff, BloodRequest, RequestStatusHistory, AgentWorkflowExecution, AgentStep and AgentApproval. Mark PKs, FKs and cardinalities. A screenshot of the EF mapping or PostgreSQL schema can support the diagram.</div>

<h1 id="s6">6. React Evidence</h1><p><code>web/src/pages/RequestsPage.tsx</code> provides the blood-bank request triage queue. It supports filtering by request status, shows blood type, quantity, hospital, urgency, notes, required-by time and current state, and offers state transitions defined for each current state. When a request is dispatched, it displays a message that stock was removed and refreshes stock-related queries. Related workflow review is represented in <code>web/src/pages/WorkflowsPage.tsx</code>.</p>
<p><b>My React contribution:</b> [state precisely what you personally implemented or reviewed. If another member owned the screen, identify your integration/testing contribution rather than claiming authorship.]</p>
<div class="evidence"><b>Insert Evidence 4 — React:</b> capture the admin request triage queue with synthetic data. Include a caption describing the displayed status/urgency and, if relevant, a second view of workflow review or a transition confirmation.</div>

<h1 id="s7">7. Flutter Evidence</h1><p>Hospital-side mobile implementation is in <code>mobile/lib/screens/hospital/requests_screen.dart</code> and <code>mobile/lib/screens/hospital/request_detail_screen.dart</code>. The list provides pull-to-refresh, request creation, required-by and status display. The detail screen loads request history and supports hospital-side edit, escalation and withdrawal actions while the request remains in pre-approval states. Form inputs and service calls are handled through the Flutter app’s shared services and validators.</p>
<p><b>My Flutter contribution:</b> [identify screens, request form fields, API calls, validation, error handling or tests you personally worked on. If no direct code contribution, state that clearly and describe your verified understanding.]</p>
<div class="evidence"><b>Insert Evidence 5 — Flutter:</b> add simulator/device screenshots of the request form and request detail/history using synthetic data. Ensure the hospital identity, notes and any account information are non-sensitive.</div>

<h1 id="s8">8. Agentic AI Contribution</h1><h2>8.1 Coordinator responsibility</h2><p>The Coordinator Agent lives in <code>agentic-ai/coordinator_agent/agent.py</code>. It calls <code>create_plan</code> with the request ID, blood type, quantity and urgency. It records a structured first step named CoordinatorAgent and places the plan into the shared graph state. It is the first node in the fixed LangGraph sequence: Coordinator, Domain Analysis, Dispatch, Validation [2].</p>
<h2>8.2 Bounded planning and fallback</h2><p><code>agentic-ai/lifelink_agents/model.py</code> asks an optional local Ollama model for JSON with an objective and an exact allow-list of three steps: analyse-domain, draft-dispatch and validate-safety. It bounds the objective length, timeout (up to ten seconds) and attempt count (up to three). A malformed response, timeout, unavailable provider or non-allow-listed step leads to a deterministic fallback plan. The model is identified in the plan so the execution is explainable at a basic operational level. The coordinator does not receive tools that approve requests, reserve stock or contact donors.</p>
<h2>8.3 Human authority and safeguards</h2><p>The Coordinator Agent organizes work; it does not decide clinical priority or authorize real-world action. Deterministic code calculates request urgency and later validates agent proposals. Human administrators approve/reject proposals through workflow endpoints. The group ADR explicitly keeps business rules and approval gates outside model authority [2].</p>
<p><b>My agent work:</b> [describe the plan schema, prompt/fallback, graph integration, agent tests or review that you personally completed. Include a concrete input and resulting plan that you can explain.]</p>
<div class="evidence"><b>Insert Evidence 6 — Agent:</b> include a code excerpt or screenshot of <code>coordinator_agent/agent.py</code> and <code>model.py</code> plus a synthetic workflow response showing the plan steps and <code>model_used</code>. Do not include internal secrets or actual patient data.</div>

<h1 id="s9">9. Testing Evidence</h1><p>Relevant test files include <code>backend/LifeLink.Tests/Requests/RequestServiceTests.cs</code>, <code>HospitalRequestLifecycleTests.cs</code>, <code>RequestApiTests.cs</code>, <code>backend/LifeLink.Tests/Workflows/WorkflowServiceTests.cs</code>, <code>WorkflowApprovalSafetyTests.cs</code>, <code>agentic-ai/tests/test_workflow.py</code>, <code>test_model_resilience.py</code> and <code>test_contract_schemas.py</code>. This report preparation inspected test source only; the suites were not run and no passing result is claimed.</p>
<table><tr><th>Test scenario evidenced in source</th><th>Purpose</th><th>Actual result to add</th></tr><tr><td>Create request calculates urgency and triggers workflow</td><td>Checks urgency floor, persistence history and trigger hand-off.</td><td>[command, date, result]</td></tr><tr><td>Unverified hospital cannot submit; hospital input normalized and validated</td><td>Checks institution gate, registration rules, enum/quantity/time bounds and UTC conversion.</td><td>[command, date, result]</td></tr><tr><td>Pre-approval edit/escalate/withdraw lifecycle</td><td>Checks permitted states, proposal supersession, pending reservation release and preservation of escalated urgency.</td><td>[command, date, result]</td></tr><tr><td>Workflow plan and model resilience</td><td>Checks schema/step contract, deterministic fallback and workflow integration.</td><td>[command, date, result]</td></tr><tr><td>Approval and dispatch safety</td><td>Checks that proposals do not silently become approved actions and stock/status changes remain coherent.</td><td>[command, date, result]</td></tr></table>
<p>Attach actual test-run or CI evidence and identify whether tests used an in-memory provider or PostgreSQL. In-memory tests do not establish row-lock, transactional or provider-specific behavior. Verify dispatch concurrency and rollback using relational integration tests before claiming those outcomes have been demonstrated.</p><div class="evidence"><b>Insert Evidence 7 — Testing:</b> attach dated output with the command, result summary and CI link. Keep failures visible and state how they were addressed.</div>

<h1 id="s10">10. Git/PR Evidence</h1><p>The local repository history available during report preparation shows only commit <code>731c58c — Initial commit: LifeLink blood and emergency coordination platform</code>. It does not establish who authored individual features or show the team’s PR review history. This does not prove that remote PRs do not exist; it means they were not available in this checkout.</p><table><tr><th>Evidence item</th><th>Student to complete</th></tr><tr><td>Name/ID mapping</td><td>[your name and ID as used in the group project]</td></tr><tr><td>Owned commits</td><td>[SHA, date, link, files/behavior changed]</td></tr><tr><td>Pull requests/reviews</td><td>[PR link, your role, review comments, merge state]</td></tr><tr><td>Tasks/issues</td><td>[board item linked to implementation and tests]</td></tr></table><p>Add a screenshot or live link for each claimed contribution. Do not use the initial commit as proof of personal ownership unless your team can verify that attribution.</p>

<h1 id="s11">11. Challenges &amp; Learning</h1><p>Use this section to record what you actually encountered. Relevant technical challenges include reconciling requested urgency with time/quantity rules; keeping UTC instants consistent across mobile, API and database; ensuring that hospital staff can only access their own hospital’s requests; defining legal status transitions; replacing an old agent proposal when request data changes; and separating model planning from human approval and inventory changes.</p><p><b>Challenge I faced:</b> [specific example].<br/><b>How I investigated it:</b> [code, test, feedback or source checked].<br/><b>What I changed or contributed:</b> [specific result and evidence].<br/><b>What I learned:</b> [your own reflection on engineering, teamwork and safe AI use].</p>

<h1 id="s12">12. Individual AI Usage Log</h1><p>This report was prepared with Codex (GPT-6) on 6 October 2026. The assistant inspected relevant repository source and tests, summarized technical behavior and drafted this Word report. It did not run tests or infer personal authorship. The student must check every technical statement, replace placeholders, add their own AI-use entries and ensure the final log matches what they actually did.</p><table><tr><th>Date</th><th>Tool/model</th><th>Task</th><th>Output used / changed</th><th>Verification</th></tr><tr><td>6 Oct 2026</td><td>Codex, GPT-6</td><td>Inspect request/triage and coordinator-agent files; prepare report.</td><td>Drafted report structure and repository-based summary. Student must verify, personalize and add evidence.</td><td>Compared statements with source files, tests and ADRs. No tests were executed and no ownership was assumed.</td></tr><tr><td>[date]</td><td>[tool/model]</td><td>[your task]</td><td>[accepted, edited or rejected output]</td><td>[independent check]</td></tr></table>

<h1 id="s13">13. AI Reflection</h1><div class="note"><b>Write this section yourself.</b> The assignment requires the AI reflection to be the student’s own writing and says AI-generated reflection will not receive credit. No first-person reflection has been generated for you.</div><p>In your own words, discuss which AI tools you used and what you asked them to do; what was helpful or wrong; what you changed or rejected and why; how you checked generated material; and what you learned about separating an AI-generated plan from accountable human decisions. Use one real example and explain your own role.</p><p>[Write approximately one page in your own words. Remove this prompt before final submission.]</p>

<h1 id="s14">14. Signed Declaration</h1><p>I declare that this report accurately describes my own contribution, distinguishes my work from work completed by others, and acknowledges sources and AI assistance. I have checked that the evidence I submit is genuine and that I can explain the work described. I have written the AI reflection myself and completed the personal fields before submission.</p><p>Student name: __________________________________________</p><p>Student ID: ______________________________________________</p><p>Signature: _______________________________________________</p><p>Date: ____________________________________________________</p>

<h1>References</h1><p>[1] LifeLink project, <i>ADR-01: Domain and agent ownership</i>, <code>docs/adr/01-domain-and-component-assignment.md</code>; request, API, client and test source cited throughout this report.</p><p>[2] LifeLink project, <i>ADR-04: Agent framework, model, and fallback</i>, <code>docs/adr/04-agentic-ai-framework-and-orchestration.md</code>; <code>agentic-ai/coordinator_agent/agent.py</code>, <code>agentic-ai/lifelink_agents/model.py</code> and <code>agentic-ai/lifelink_agents/graph.py</code>.</p><p>[3] PostgreSQL Global Development Group, <i>Constraints</i>, <a href="https://www.postgresql.org/docs/current/ddl-constraints.html">https://www.postgresql.org/docs/current/ddl-constraints.html</a> (accessed 6 October 2026).</p><p>[4] Microsoft, <i>Concurrency Tokens</i>, Entity Framework Core documentation, <a href="https://learn.microsoft.com/en-us/ef/core/saving/concurrency">https://learn.microsoft.com/en-us/ef/core/saving/concurrency</a> (accessed 6 October 2026). Referenced for general background; project behavior claims are based on the repository.</p><p>[5] LangChain, <i>LangGraph Overview</i>, <a href="https://docs.langchain.com/oss/python/langgraph/overview">https://docs.langchain.com/oss/python/langgraph/overview</a> (accessed 6 October 2026).</p><p>[6] Ollama, <i>Generate a completion</i>, <a href="https://docs.ollama.com/api/generate">https://docs.ollama.com/api/generate</a> (accessed 6 October 2026).</p><p><a href="#contents">Return to Contents</a></p>
</body></html>
'@
[System.IO.File]::WriteAllText($htmlPath, $html, [System.Text.UTF8Encoding]::new($false))
Add-Type -AssemblyName System.IO.Compression
if (Test-Path -LiteralPath $outPath) { Remove-Item -LiteralPath $outPath -Force }
$stream = [System.IO.File]::Open($outPath, [System.IO.FileMode]::CreateNew)
$zip = [System.IO.Compression.ZipArchive]::new($stream, [System.IO.Compression.ZipArchiveMode]::Create, $false)
try {
  $entries = @{
    '[Content_Types].xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="htm" ContentType="text/html"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'
    '_rels/.rels' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'
    'word/document.xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body><w:altChunk r:id="rId2"/><w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1020" w:right="1134" w:bottom="1020" w:left="1134"/></w:sectPr></w:body></w:document>'
    'word/_rels/document.xml.rels' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/aFChunk" Target="afchunk.htm"/></Relationships>'
  }
  foreach ($entryName in $entries.Keys) { $entry=$zip.CreateEntry($entryName,[System.IO.Compression.CompressionLevel]::Optimal); $writer=[System.IO.StreamWriter]::new($entry.Open(),[System.Text.UTF8Encoding]::new($false)); try{$writer.Write($entries[$entryName])}finally{$writer.Dispose()} }
  $entry=$zip.CreateEntry('word/afchunk.htm',[System.IO.Compression.CompressionLevel]::Optimal); $writer=[System.IO.StreamWriter]::new($entry.Open(),[System.Text.UTF8Encoding]::new($false)); try{$writer.Write($html)}finally{$writer.Dispose()}
} finally { $zip.Dispose(); $stream.Dispose() }
Remove-Item -LiteralPath $htmlPath -Force
Write-Output $outPath
