import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { api } from '../api/client'
import { QueryState, StatusPill, formatDate } from '../components/QueryState'
import { Icon, type IconName } from '../components/Icon'
export function DashboardPage(){
 const summary=useQuery({queryKey:['request-summary'],queryFn:api.requests.summary});const workflows=useQuery({queryKey:['workflows','dashboard'],queryFn:()=>api.workflows.list()});const stock=useQuery({queryKey:['stock-report'],queryFn:api.inventory.report})
 const loading=summary.isLoading||workflows.isLoading||stock.isLoading;const error=summary.error||workflows.error||stock.error
 const grouped=Object.entries((stock.data??[]).reduce<Record<string,number>>((all,row)=>{all[row.bloodType]=(all[row.bloodType]??0)+row.availableUnits;return all},{}));const max=Math.max(1,...grouped.map(([,units])=>units))
 const metrics: {label:string;value:number;note:string;icon:IconName}[]=[{label:'Open requests',value:summary.data?.open??0,note:`${summary.data?.critical??0} open requests marked critical`,icon:'requests'},{label:'Pending approvals',value:workflows.data?.filter(x=>x.status==='PendingApproval').length??0,note:'Waiting for your review',icon:'workflow'},{label:'Available units',value:stock.data?.reduce((sum,x)=>sum+x.availableUnits,0)??0,note:`Across ${new Set(stock.data?.map(x=>x.locationId)).size} storage locations`,icon:'drop'},{label:'Fulfilled requests',value:summary.data?.fulfilled??0,note:'Care delivered, recorded',icon:'shield'}]
 return <><header className="page-header"><div><p className="eyebrow">A connected network. A shared purpose.</p><h1>Command overview</h1><p>A clear picture of your network, and what needs you next.</p></div><span className="live-chip"><i/>{error?'Connection needs attention':loading?'Connecting…':'Latest available data'}</span></header><section className="welcome-banner"><p className="eyebrow">Every connection makes a difference</p><h2>Better coordinated.<br/>More lives connected.</h2><p>Keep essential blood supplies moving and help the right care reach the right people.</p><Link to="/requests">Explore requests <Icon name="arrow"/></Link><span className="banner-tag">One network. Many lifelines.</span></section><QueryState loading={loading} error={error}><div className="metric-grid">{metrics.map(item=><article key={item.label}><Icon name={item.icon}/><span>{item.label}</span><strong>{item.value}</strong><small>{item.note}</small></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><div><p className="eyebrow">Your attention matters</p><h2>Recent AI workflows</h2></div><Link to="/workflows">View all →</Link></div><div className="activity-list">{workflows.data?.slice(0,5).map(flow=><div key={flow.id}><span className="activity-icon"><Icon name="workflow"/></span><div><strong>{flow.objective}</strong><small>{formatDate(flow.startedAtUtc)} · Attempt {flow.attemptNumber}</small></div><StatusPill value={flow.status}/></div>)}</div>{!workflows.data?.length&&<p className="inline-empty">No workflows yet. New coordination activity will appear here.</p>}</section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Ready when it matters</p><h2>Blood supply at a glance</h2></div><Link to="/inventory">Inventory →</Link></div><div className="stock-bars">{grouped.map(([type,units])=><div key={type}><span>{type.replace('Positive','+').replace('Negative','−')}</span><div><i style={{width:`${units/max*100}%`}}/></div><strong>{units}</strong></div>)}</div>{grouped.length?<p className="chart-note">Available units across all locations · Bars relative to the largest group</p>:<p className="inline-empty">No stock recorded yet. Receive your first lot in Inventory.</p>}</section></div></QueryState><section className="quick-links" aria-label="Quick actions"><Link to="/donors"><Icon name="donors"/>Donor registry<Icon name="arrow"/></Link><Link to="/camps"><Icon name="calendar"/>Plan a donation camp<Icon name="arrow"/></Link><Link to="/hospitals"><Icon name="hospital"/>Review hospitals<Icon name="arrow"/></Link></section></>
}
