import { useState, type FormEvent } from 'react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthContext'
import { homeFor } from '../features/auth/ProtectedRoute'
import { Icon } from '../components/Icon'
import { ThemeToggle } from '../components/ThemeToggle'
export function LoginPage() {
 const { user, login, sessionExpired } = useAuth(); const navigate = useNavigate(); const location = useLocation()
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [visible,setVisible]=useState(false)
 if(user) return <Navigate to={homeFor(user.role)} replace />
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await login(email,password);const target=(location.state as {from?:{pathname?:string}}|null)?.from?.pathname;if(target)navigate(target,{replace:true})}catch(reason){setError(reason instanceof Error?reason.message:'Sign in failed.')}finally{setBusy(false)}}
 return <main className="login-page"><section className="login-story"><div className="brand"><span className="brand-mark"><Icon name="drop" /></span><span>LifeLink<small>Care. Connected.</small></span></div><div><p className="eyebrow">Together, we keep life moving</p><h1>Every minute.<br/>Every match.<br/><em>One lifeline.</em></h1><p>A connected network of people, hospitals and possibility. Bring life-saving care a little closer.</p></div><small>THE BLOOD & EMERGENCY NETWORK · SRI LANKA</small></section><section className="login-card"><div className="login-theme"><ThemeToggle/></div><form onSubmit={submit}><div className="brand mobile-brand"><span className="brand-mark"><Icon name="drop"/></span><span>LifeLink<small>Care. Connected.</small></span></div><p className="eyebrow">Your care coordination workspace</p><h2>Welcome back</h2><p>A little coordination. A life-changing difference.<br/>Sign in with your LifeLink account.</p>{sessionExpired&&!error&&<div className="form-notice" role="status">Your session ended. Please sign in again.</div>}<label>Email address<input autoComplete="username" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="admin@lifelink.lk"/></label><label>Password<span className="password-field"><input aria-label="Password" autoComplete="current-password" type={visible?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Enter your password"/><button type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?'Hide':'Show'}</button></span></label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="primary-button" disabled={busy}>{busy?'Signing in…':'Sign in securely'}<Icon name="arrow"/></button><p className="login-switch">New to LifeLink? <Link to="/register">Create a donor or hospital account</Link></p><div className="login-assurance"><Icon name="shield"/>Protected access. Human-led decisions.</div></form></section></main>
}

