import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/client'
import type { BloodRequestStatus } from '../api/types'
import { QueryState, StatusPill, formatDate } from '../components/QueryState'
import { refreshStock } from './InventoryPage'

const next: Partial<Record<BloodRequestStatus, BloodRequestStatus[]>> = { Submitted: ['UnderReview', 'Escalated', 'ClosedUnfulfilled'], UnderReview: ['PendingApproval', 'Escalated', 'ClosedUnfulfilled'], PendingApproval: ['Approved', 'Escalated', 'ClosedUnfulfilled'], Approved: ['Dispatched', 'ClosedUnfulfilled'], Dispatched: ['Fulfilled', 'ClosedUnfulfilled'], Escalated: ['UnderReview', 'PendingApproval', 'ClosedUnfulfilled'] }
export function RequestsPage() {
  const [status, setStatus] = useState<BloodRequestStatus | ''>(''); const queryClient = useQueryClient(); const query = useQuery({ queryKey: ['requests', status], queryFn: () => api.requests.list(status || undefined) })
  const [notice, setNotice] = useState('')
  const transition = useMutation({ mutationFn: ({ id, status }: { id: string; status: BloodRequestStatus }) => api.requests.transition(id, status, 'Updated from admin triage queue.'), onMutate: () => setNotice(''), onSuccess: item => { setNotice(item.status === 'Dispatched' ? `${item.quantityUnits} unit(s) for ${item.hospitalName} were taken out of stock and dispatched.` : `Request for ${item.hospitalName} moved to ${item.status.replace(/([a-z])([A-Z])/g, '$1 $2')}.`); queryClient.invalidateQueries({ queryKey: ['requests'] }); queryClient.invalidateQueries({ queryKey: ['request-summary'] }); if (item.status === 'Dispatched') refreshStock(queryClient) } })
  return <><header className="page-header"><div><p className="eyebrow">Hospital demand</p><h1>Request triage</h1><p>Review urgency, advance safe transitions and watch required-by times.</p></div><span className="count-chip">{query.data?.totalCount ?? 0} requests</span></header><section className="toolbar"><select aria-label="Request status" value={status} onChange={e => setStatus(e.target.value as BloodRequestStatus | '')}><option value="">All request states</option>{Object.keys(next).map(value => <option key={value}>{value}</option>)}<option>Fulfilled</option><option>ClosedUnfulfilled</option></select></section>{transition.error && <div className="form-error" role="alert">{transition.error.message}</div>}{notice && <div className="form-notice" role="status">{notice}</div>}<QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length} onRetry={() => query.refetch()}><section className="request-grid">{query.data?.items.map(item => <article className={`request-card urgency-${item.urgency.toLowerCase()}`} key={item.id}><div className="request-top"><span className="blood-badge large">{item.bloodType.replace('Positive', '+').replace('Negative', '-')}</span><div><strong>{item.quantityUnits} unit{item.quantityUnits === 1 ? '' : 's'}</strong><small>{item.hospitalName}</small></div><StatusPill value={item.urgency} /></div><p>{item.notes || 'No clinical notes supplied.'}</p><div className="request-meta"><span>Required {formatDate(item.requiredByUtc)}</span><StatusPill value={item.status} /></div>{next[item.status]?.length ? <select aria-label={`Transition ${item.id}`} disabled={transition.isPending} defaultValue="" onChange={e => { if (e.target.value) transition.mutate({ id: item.id, status: e.target.value as BloodRequestStatus }); e.target.value = '' }}><option value="" disabled>Advance status…</option>{next[item.status]!.map(value => <option key={value} value={value}>{value === 'Dispatched' ? 'Dispatched (takes units from stock)' : value.replace(/([a-z])([A-Z])/g, '$1 $2')}</option>)}</select> : null}</article>)}</section></QueryState></>
}
